-- CRIAR BANCO DE DADOS
 CREATE DATABASE Gufi_Tarde;

 -- DEFINE QUAL BANCO DE DATOS ESTÁ SENDO USADO
 USE Gufi_Tarde;

 -- CRIA AS TABELAS
 CREATE TABLE TipoUsuario(
	IdTipoUsuario		INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario	VARCHAR (50) NOT NULL UNIQUE
 );

 CREATE TABLE TipoEvento (
	IdTipoEvento		INT PRIMARY KEY IDENTITY,
	TituloTipoEvento	VARCHAR (100) NOT NULL UNIQUE
 );

 CREATE TABLE Instituicao (
	IdInstituicao		INT PRIMARY KEY IDENTITY,
	Cnpj				CHAR (14) NOT NULL UNIQUE,
	NomeFantasia		VARCHAR	(100) NOT NULL UNIQUE,
	Endereco			VARCHAR (100) NOT NULL UNIQUE
 );

 CREATE TABLE Usuario (
	IdUsuario			INT PRIMARY KEY IDENTITY,
	IdTipoUsuario		INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario),
	NomeUsuario			VARCHAR (100) NOT NULL,
	Email				VARCHAR (100) NOT NULL UNIQUE,
	Senha				VARCHAR (100) NOT NULL,
	Genero				VARCHAR (100) NOT NULL,
	DataNascimento		DATETIME2 NOT NULL
 );

 CREATE TABLE Evento (
	IdEvento			INT PRIMARY KEY IDENTITY,
	IdInstituicao		INT FOREIGN KEY REFERENCES Instituicao (IdInstituicao),
	IdTipoEvento		INT FOREIGN KEY REFERENCES TipoEvento (IdTipoEvento),
	NomeEvento			VARCHAR (100) NOT NULL,
	Descricao			VARCHAR (100) NOT NULL,
	DataEvento			DATETIME2 NOT NULL,
	AcessoLivro			BIT DEFAULT (1), 
 );

 CREATE TABLE Presenca (
	IdPresenca			INT PRIMARY KEY IDENTITY,
	IdUsuario			INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
	IdEvento			INT FOREIGN KEY REFERENCES Evento (IdEvento),
	Situacao			VARCHAR (50)
 );
